FROM node:20-alpine

RUN apk add --no-cache openssl libc6-compat

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/
COPY tsconfig.json nest-cli.json ./

RUN npm ci && npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
