export const ErrorCodes = {
  // Auth
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH',
  SAME_PASSWORD: 'SAME_PASSWORD',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_EMPLOYEE_ID: 'DUPLICATE_EMPLOYEE_ID',

  // Roles
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  SYSTEM_ROLE_PROTECTED: 'SYSTEM_ROLE_PROTECTED',
  ROLE_HAS_USERS: 'ROLE_HAS_USERS',

  // Permissions
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',

  // Assets
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  DUPLICATE_SERIAL_NUMBER: 'DUPLICATE_SERIAL_NUMBER',
  DUPLICATE_ASSET_CODE: 'DUPLICATE_ASSET_CODE',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DISPOSAL_REQUIRES_SANITIZATION: 'DISPOSAL_REQUIRES_SANITIZATION',
  CANNOT_DELETE_ASSIGNED_ASSET: 'CANNOT_DELETE_ASSIGNED_ASSET',
  ASSET_ALREADY_ASSIGNED: 'ASSET_ALREADY_ASSIGNED',

  // Categories
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_ASSETS: 'CATEGORY_HAS_ASSETS',

  // Assignments
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',

  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
