export enum ActivityAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  ASSIGN = 'ASSIGN',
  RETURN = 'RETURN',
  TRANSFER = 'TRANSFER',
  EXPORT = 'EXPORT',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
}
